@CarRental_BE_HostAddress = http://localhost:5227

GET {{CarRental_BE_HostAddress}}/weatherforecast/
Accept: application/json

###
GET http://localhost:5227/api/Car/test-connection
Accept: application/json

###
GET http://localhost:5227/api/Car/All
Accept: application/json

###
POST http://localhost:5227/api/Auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "user1@example.com",
  "password": "@Quanquan3007"
}

###
GET http://localhost:5227/api/User/profile/3E90353C-1C5D-469E-A572-0579A1C0468D
Accept: application/json
###
PUT http://localhost:5227/api/User/profile/3E90353C-1C5D-469E-A572-0579A1C0468D
Content-Type: application/json
Accept: application/json

{
  "fullName": "Nguyen Van ABC",
  "dob": "1995-06-15",
  "phoneNumber": "0987654321",
  "nationalId": "123456789",
  "drivingLicenseUri": "http://example.com/license.jpg",
  "houseNumberStreet": "123 Nguyen Trai",
  "ward": "Phường Duyên Hải",
  "district": "Thành phố Lào Cai",
  "cityProvince": "Tỉnh Lào Cai"
}


#call to get all cars
###
GET http://localhost:5227/api/Car/3E90353C-1C5D-469E-A572-0579A1C0468D
Content-Type: application/json
Accept: application/json
}

##Lấy trang đầu tiên, 10 records mỗi trang
###
GET http://localhost:5227/api/Car/3E90353C-1C5D-469E-A572-0579A1C0468D/paginated?pageNumber=1&pageSize=10

#Lấy trang thứ 2, 5 records mỗi trang
###
GET http://localhost:5227/api/Car/3E90353C-1C5D-469E-A572-0579A1C0468D/paginated?pageNumber=2&pageSize=5

#default pageNumber=1, pageSize=10
###
GET http://localhost:5227/api/Car/3E90353C-1C5D-469E-A572-0579A1C0468D/paginated


###
POST http://localhost:5227/api/User/change-password/3E90353C-1C5D-469E-A572-0579A1C0468D
Content-Type: application/json
Accept: application/json

{
  "currentPassword": "hashed_password_1",
  "newPassword": "new_secure_password",
  "confirmPassword": "new_secure_password"
}