@CarRental_BE_HostAddress = http://localhost:5227

GET {{CarRental_BE_HostAddress}}/weatherforecast/
Accept: application/json

###
GET http://localhost:5227/api/Car/test-connection
Accept: application/json

###
GET http://localhost:5227/api/Car/All
Accept: application/json

###
POST http://localhost:5227/api/Auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "user1@example.com",
  "password": "hashed_password_1"
}
